global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'propostas'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['propostas-api:8080']